export const inputs = [
    {
        id: 1,
        name: "username",
        type: "text",
        placeholder: "Username",
        label: "Username",
        errorMessage: "Username should be 3-16 characters and shouldn't include any special character.",
        required: true,
    },
    {
        id: 2,
        name: "email",
        type: "text",
        placeholder: "Email",
        label: "Email",
        errorMessage: "It should be a valid email address.",
        required: true,
    },
    {
        id: 3,
        name: "password",
        type: "password",
        placeholder: "Password",
        label: "Password",
        errorMessage: "Password should be 8 or more characters",
        required: true,
    },
    {
        id: 4,
        name: "confirmPassword",
        type: "password",
        placeholder: "Confirm password",
        label: "Confirm password",
        errorMessage: "Passwords don't match.",
        required: true,
    },
];